---
- name: "Build and run a Docker container"
  hosts: localhost
  connection: local
  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_password: "{{ dockerhub_password }}"
  tasks:
    - name: Stop current running container if it exists
      docker_container:
        name: web-container
        state: stopped
      ignore_errors: yes

    - name: Remove the stopped container if it exists
      docker_container:
        name: web-container
        state: absent
      ignore_errors: yes

    - name: Remove existing Docker image if it exists
      command: docker rmi amer30004ever/proj
      ignore_errors: yes

    - name: Build Docker image using the Dockerfile
      command: docker build -t amer30004ever/proj .

    - name: Log in to DockerHub
      docker_login:
        username: "{{ lookup('env', 'dockerhub_username') }}"
        password: "{{ lookup('env', 'dockerhub_password') }}"


    - name: Push the Docker image to DockerHub
      command: docker push amer30004ever/proj

    - name: Run the Docker container
      docker_container:
        name: web-container
        image: amer30004ever/proj
        state: started
        ports:
          - "5000:80"
