---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove proj-image
      command: docker rmi amer30004ever/proj
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t amer30004ever/proj .

    - name: Push Image to dockerhub
      command: docker push amer30004ever/proj

    - name: run container
      command: docker run -d --name web-container -p 5000:80 amer30004ever/proj

