---
- name: Deploy Product Service
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      tags: docker

    - name: Ensure Docker Compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      tags: docker-compose

    - name: Copy application files for product service
      copy:
        src: /mnt/data/product/
        dest: /usr/src/app/product/
        mode: '0755'
      tags: copy-files

    - name: Copy application files for website
      copy:
        src: /mnt/data/website/
        dest: /usr/src/app/website/
        mode: '0755'
      tags: copy-files

    - name: Create docker-compose.yml
      copy:
        content: |
          version: '3'
          services:
            product-service:
              build: /usr/src/app/product
              volumes:
                - /usr/src/app/product:/usr/src/app
              ports:
                - "5001:80"
            website:
              image: php:7.4-apache
              volumes:
                - /usr/src/app/website:/var/www/html
              ports:
                - "5000:80"
              depends_on:
                - product-service
        dest: /usr/src/app/docker-compose.yml
        mode: '0755'
      tags: docker-compose

    - name: Start containers
      command: docker-compose up -d
      args:
        chdir: /usr/src/app
      tags: start-containers
